#ifndef _LLVM_H_
#define _LLVM_H_

//#include <llvm-c/Analysis.h>
//#include <llvm-c/BitReader.h>
//#include <llvm-c/BitWriter.h>
//#include <llvm-c/Core.h>
//#include <llvm-c/Disassembler.h>
//#include <llvm-c/ErrorHandling.h>
//#include <llvm-c/ExecutionEngine.h>
//#include <llvm-c/Initialization.h>
//#include <llvm-c/IRReader.h>
//#include <llvm-c/Linker.h>
//#include <llvm-c/LinkTimeOptimizer.h>
//#include <llvm-c/lto.h>
//#include <llvm-c/Object.h>
//#include <llvm-c/OrcBindings.h>
//#include <llvm-c/Support.h>
//#include <llvm-c/Target.h>
//#include <llvm-c/TargetMachine.h>
//#include <llvm-c/Transforms/IPO.h>
//#include <llvm-c/Transforms/PassManagerBuilder.h>
//#include <llvm-c/Transforms/Scalar.h>
//#include <llvm-c/Transforms/Vectorize.h>
//#include <llvm-c/Types.h>

#include "/usr/local/include/llvm-c/Analysis.h"
#include "/usr/local/include/llvm-c/BitReader.h"
#include "/usr/local/include/llvm-c/BitWriter.h"
#include "/usr/local/include/llvm-c/Core.h"
#include "/usr/local/include/llvm-c/Disassembler.h"
#include "/usr/local/include/llvm-c/ErrorHandling.h"
#include "/usr/local/include/llvm-c/ExecutionEngine.h"
#include "/usr/local/include/llvm-c/Initialization.h"
#include "/usr/local/include/llvm-c/IRReader.h"
#include "/usr/local/include/llvm-c/Linker.h"
#include "/usr/local/include/llvm-c/LinkTimeOptimizer.h"
#include "/usr/local/include/llvm-c/lto.h"
#include "/usr/local/include/llvm-c/Object.h"
#include "/usr/local/include/llvm-c/OrcBindings.h"
#include "/usr/local/include/llvm-c/Support.h"
#include "/usr/local/include/llvm-c/Target.h"
#include "/usr/local/include/llvm-c/TargetMachine.h"
#include "/usr/local/include/llvm-c/Transforms/IPO.h"
#include "/usr/local/include/llvm-c/Transforms/PassManagerBuilder.h"
#include "/usr/local/include/llvm-c/Transforms/Scalar.h"
#include "/usr/local/include/llvm-c/Transforms/Vectorize.h"
#include "/usr/local/include/llvm-c/Types.h"

#endif // _LLVM_H_
