#define __STDC_LIMIT_MACROS
#define __STDC_CONSTANT_MACROS

#import <llvm-c/Analysis.h>
#import <llvm-c/BitReader.h>
#import <llvm-c/BitWriter.h>
#import <llvm-c/Core.h>
#import <llvm-c/Disassembler.h>
#import <llvm-c/ErrorHandling.h>
#import <llvm-c/ExecutionEngine.h>
#import <llvm-c/Initialization.h>
#import <llvm-c/IRReader.h>
#import <llvm-c/Linker.h>
#import <llvm-c/LinkTimeOptimizer.h>
#import <llvm-c/Object.h>
#import <llvm-c/OrcBindings.h>
#import <llvm-c/Support.h>
#import <llvm-c/Target.h>
#import <llvm-c/TargetMachine.h>
#import <llvm-c/Transforms/IPO.h>
#import <llvm-c/Transforms/PassManagerBuilder.h>
#import <llvm-c/Transforms/Scalar.h>
#import <llvm-c/Transforms/Vectorize.h>
#import <llvm-c/Types.h>
